Repository SrajanAgrawal/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Add files via upload
  Linked_list_using_c.c
Labels: hacktoberfest, good first contribution, Hacktoberfest approved

#5 Create sudoku.cpp
  sudoku.cpp
Labels: hacktoberfest, Hacktoberfest approved

#4 Create BerlinClock.py
  python/BerlinClock.py
Labels: hacktoberfest, Hacktoberfest approved

#3 Contribute merge sort algorithm in java
  Linked_list_using_c.c
  Merge_sort.java
Labels: hacktoberfest, Hacktoberfest approved

#2 Add MergeSort in java
  MergeSort.java
Labels: hacktoberfest, Hacktoberfest approved

#9 Create BinarySearch.java
  Java/BinarySearch.java
Labels: hacktoberfest, Hacktoberfest approved

#8 Create reverse.py
  python/reverse.py
Labels: hacktoberfest, Hacktoberfest approved

#7 Added bubble and selection sort
  Java/Bubble.java
  Java/Selection.java
Labels: hacktoberfest, Hacktoberfest approved

#6 Added Program to check Armstrong number in C
  check_Armstrong_number.c
Labels: hacktoberfest, Hacktoberfest approved

#22 linked-list/Reverse list/Using pointer
  C++/Reverse_list.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#21 added next/prev Smaller element in cpp
  C++/nextSmallerElement.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#49 Added Sieve Of Eratosthenes
  C++/queue.cpp
  C/check_Armstrong_number.c
  python/prime_sieve.py
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#60 gcd.cpp
  gcd.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#82 Create SelectionSort.py
  python/SelectionSort.py
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#81 Update Contribution.md
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#80 Add files via upload
  C++/Function_to_delete_linkedlist
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#79 Added breadth first search.
  C++/breadth_first_search.cpp
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#78 Create sort_merge
  Java/sort_merge
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#76 Palindrome Number Checker in C
  C/Palindrome Number.c
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#83 Job_Scheduling_Algorithm
  C++/JobScheduling.cpp
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#73 Added Cyclic sort in java
  Contribution.md
  Java/Cyclicsorting.java
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#72 hacktoberfest 2022
  C/REMOVE DUPLICATE NODE IN SLL
  C/calculate premutation.c
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#71 Changed header
  C++/deletion_in_array.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#70 ADD KMP Algo In CPP
  C++/KMP.cpp
  C++/KMP.exe
  Java/binary.java
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#84 Create sum.cpp
  C++/sum.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#69 Create 2sum.cpp
  C++/2sum.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#68 Create workingcountalgo.cpp
  C++/workingcountalgo.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#67 Added tower of hanoi code in cpp
  C++/tower-of-hanoi.cpp
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#55 Bubble Sort
  C/bubble_sort/Sourodip20kar.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#56 Add python program that encrypts a string
  Contribution.md
  python/caesar.py
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#57 Graph Traversal
  C++/BFS.cpp
  C++/DFS.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#58 Create LCM.cpp
  LCM.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#59 factorial.cpp
  factorial.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#62 rename a new file in python folder
  python/random password generator.py
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#63 Create Insertionsort.cpp
  C++/Insertionsort.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#64 Create Longest Common subSequence
  Longest Common subSequence
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#65 Sorting Character by Frequency ✔
  C++/SortCharacter By Frequency
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#66 Create Valid_Parenthese.cpp
  C++/Valid_Parenthese.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#85 Create BubbleSort.cpp
  C++/BubbleSort.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#77 Update Contribution.md
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#19 Update Contribution.md
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#17 Create Contribution.md
  Contribution.md
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#86 Added Pascal triangle
  Java/pascal-triangle.java
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#87 Printing LCS
  Java/Printing LCS
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#116 Create stackgame.java
  Java/stackgame.java
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#108 SearchingElementInMatrix
  Java/SearchingElementInMatrix.java
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted

#118 Create Program.cpp
  C++/Program.cpp
Labels: hacktoberfest, Hacktoberfest approved, hacktoberfest-accepted
